# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/eb/Documents/bo/pyDataman/ui_files/mainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_mainwindow(object):
    def setupUi(self, mainwindow):
        mainwindow.setObjectName("mainwindow")
        mainwindow.resize(676, 595)
        self.centralwidget = QtWidgets.QWidget(mainwindow)
        self.centralwidget.setObjectName("centralwidget")
        self.userName = QtWidgets.QLineEdit(self.centralwidget)
        self.userName.setGeometry(QtCore.QRect(20, 60, 191, 31))
        self.userName.setObjectName("userName")
        self.phoneNumber = QtWidgets.QLineEdit(self.centralwidget)
        self.phoneNumber.setGeometry(QtCore.QRect(220, 60, 191, 31))
        self.phoneNumber.setObjectName("phoneNumber")
        self.firstName = QtWidgets.QLineEdit(self.centralwidget)
        self.firstName.setGeometry(QtCore.QRect(20, 110, 191, 31))
        self.firstName.setObjectName("firstName")
        self.addres = QtWidgets.QLineEdit(self.centralwidget)
        self.addres.setGeometry(QtCore.QRect(220, 110, 191, 31))
        self.addres.setObjectName("addres")
        self.mainTable = QtWidgets.QTableWidget(self.centralwidget)
        self.mainTable.setGeometry(QtCore.QRect(20, 160, 641, 361))
        self.mainTable.setObjectName("mainTable")
        self.mainTable.setColumnCount(5)
        self.mainTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.mainTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.mainTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.mainTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.mainTable.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.mainTable.setHorizontalHeaderItem(4, item)
        self.mainTable.horizontalHeader().setStretchLastSection(True)
        self.approved = QtWidgets.QCheckBox(self.centralwidget)
        self.approved.setGeometry(QtCore.QRect(420, 120, 121, 20))
        self.approved.setObjectName("approved")
        self.addData = QtWidgets.QPushButton(self.centralwidget)
        self.addData.setGeometry(QtCore.QRect(550, 100, 111, 51))
        self.addData.setObjectName("addData")
        self.removeRow = QtWidgets.QPushButton(self.centralwidget)
        self.removeRow.setGeometry(QtCore.QRect(550, 50, 111, 51))
        self.removeRow.setObjectName("removeRow")
        mainwindow.setCentralWidget(self.centralwidget)
        self.mainMenubar = QtWidgets.QMenuBar(mainwindow)
        self.mainMenubar.setGeometry(QtCore.QRect(0, 0, 676, 22))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mainMenubar.sizePolicy().hasHeightForWidth())
        self.mainMenubar.setSizePolicy(sizePolicy)
        self.mainMenubar.setAutoFillBackground(True)
        self.mainMenubar.setDefaultUp(False)
        self.mainMenubar.setNativeMenuBar(False)
        self.mainMenubar.setObjectName("mainMenubar")
        self.menuFile = QtWidgets.QMenu(self.mainMenubar)
        self.menuFile.setObjectName("menuFile")
        self.menuEdit = QtWidgets.QMenu(self.mainMenubar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuHelp = QtWidgets.QMenu(self.mainMenubar)
        self.menuHelp.setObjectName("menuHelp")
        mainwindow.setMenuBar(self.mainMenubar)
        self.mainStatusbar = QtWidgets.QStatusBar(mainwindow)
        self.mainStatusbar.setObjectName("mainStatusbar")
        mainwindow.setStatusBar(self.mainStatusbar)
        self.mainToolBar = QtWidgets.QToolBar(mainwindow)
        self.mainToolBar.setObjectName("mainToolBar")
        mainwindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.actionExport = QtWidgets.QAction(mainwindow)
        self.actionExport.setObjectName("actionExport")
        self.actionImport = QtWidgets.QAction(mainwindow)
        self.actionImport.setObjectName("actionImport")
        self.actionExit = QtWidgets.QAction(mainwindow)
        self.actionExit.setObjectName("actionExit")
        self.actionPreferences = QtWidgets.QAction(mainwindow)
        self.actionPreferences.setObjectName("actionPreferences")
        self.actionAbout = QtWidgets.QAction(mainwindow)
        self.actionAbout.setObjectName("actionAbout")
        self.menuFile.addAction(self.actionExport)
        self.menuFile.addAction(self.actionImport)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuEdit.addAction(self.actionPreferences)
        self.menuHelp.addAction(self.actionAbout)
        self.mainMenubar.addAction(self.menuFile.menuAction())
        self.mainMenubar.addAction(self.menuEdit.menuAction())
        self.mainMenubar.addAction(self.menuHelp.menuAction())
        self.mainToolBar.addAction(self.actionExport)
        self.mainToolBar.addAction(self.actionImport)
        self.mainToolBar.addSeparator()
        self.mainToolBar.addAction(self.actionPreferences)
        self.mainToolBar.addSeparator()
        self.mainToolBar.addAction(self.actionExit)

        self.retranslateUi(mainwindow)
        QtCore.QMetaObject.connectSlotsByName(mainwindow)

    def retranslateUi(self, mainwindow):
        _translate = QtCore.QCoreApplication.translate
        mainwindow.setWindowTitle(_translate("mainwindow", "PyDataman 0.1"))
        self.userName.setPlaceholderText(_translate("mainwindow", "User Name"))
        self.phoneNumber.setPlaceholderText(_translate("mainwindow", "Phone Number"))
        self.firstName.setPlaceholderText(_translate("mainwindow", "First Name"))
        self.addres.setPlaceholderText(_translate("mainwindow", "Addres"))
        item = self.mainTable.horizontalHeaderItem(0)
        item.setText(_translate("mainwindow", "User Name"))
        item = self.mainTable.horizontalHeaderItem(1)
        item.setText(_translate("mainwindow", "First Name"))
        item = self.mainTable.horizontalHeaderItem(2)
        item.setText(_translate("mainwindow", "Phone Number"))
        item = self.mainTable.horizontalHeaderItem(3)
        item.setText(_translate("mainwindow", "Addres"))
        item = self.mainTable.horizontalHeaderItem(4)
        item.setText(_translate("mainwindow", "Status"))
        self.approved.setText(_translate("mainwindow", "User Approved"))
        self.addData.setText(_translate("mainwindow", "Add Data"))
        self.removeRow.setText(_translate("mainwindow", "Remove Row"))
        self.menuFile.setTitle(_translate("mainwindow", "File"))
        self.menuEdit.setTitle(_translate("mainwindow", "Edit"))
        self.menuHelp.setTitle(_translate("mainwindow", "Help"))
        self.mainToolBar.setWindowTitle(_translate("mainwindow", "toolBar"))
        self.actionExport.setText(_translate("mainwindow", "Export"))
        self.actionImport.setText(_translate("mainwindow", "Import"))
        self.actionExit.setText(_translate("mainwindow", "Exit"))
        self.actionPreferences.setText(_translate("mainwindow", "Preferences"))
        self.actionAbout.setText(_translate("mainwindow", "About"))

